def welcome():
    div()
    print("Thank you for downloading Pythinux.")
    div()
    print("Here are some common commands which might interest you:")
    print("* help")
    print("    * Provides a list of commands.")
    print("* man")
    print("    * Manual display system.")
    print("* pkm")
    print("    * package manager for pythinux programs.")
    div()
    print("If you would like someone to help you, go to:")
    print("https://codeberg.org/Pythinux/Pythinux")
    print("and make an Issue.")
    div()
    print("Alternatively, the official Pythinux wiki (https://pythinux.codeberg.page/wiki) could also provide helpful material for more technical users.")
    div()

def main(args):
    welcome()
